### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by maedoc** [maedoc/pycmdstan#2]
or brainstorming where to go with this module: 

- [ ] wrap densities
- [ ] wrap data types and typical functions
- [ ] decorator to translate Python syntax to Stan syntax
- [ ] translate Py syntax model to Stan in background
- [ ] precompiled algos call Py callable for faster model iteration
